version: 0.2

phases:
  pre_build:
    commands:
      - echo Running JUnit tests on `date`
      - mvn test

  build:
    commands:
      - echo Maven build started on `date`
      - mvn clean package
      
artifacts:
  files:
    - target/servlet-mockito-0.0.1-SNAPSHOT.war
    - .ebextensions/**/*
  
eb_codebuild_settings:
  CodeBuildServiceRole: AWS-Pipeline-Service
  ComputeType: BUILD_GENERAL1_SMALL
  Image: aws/codebuild/java:openjdk-8